# Generated by Django 3.2 on 2022-06-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220606_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=8),
        ),
    ]
